### ISSUE TITLE
Unsatisfiable requirement: SpecialFunctions

### ISSUE THREAD

**Issue by RCCWang** [JuliaGraphics/ColorVectorSpace.jl#121]
Hi,

I had problems installing Luxor, Images, and a few other Julia packages that requires this package. I traced the problem to the fact that

`add ColorVectorSpace`

would install a v0.9.0 version of SpecialFunctions. I have a newer version of SpecialFunctions (v0.10.0) installed in my Julia set up. The following is the error I'd get:
`ERROR: Unsatisfiable requirements detected for package SpecialFunctions [276daf66]:
 SpecialFunctions [276daf66] log:
 ├─possible versions are: [0.7.0-0.7.2, 0.8.0, 0.9.0, 0.10.0] or uninstalled
 ├─restricted to versions 0.10.0 by an explicit requirement, leaving only versions 0.10.0
 └─restricted by compatibility requirements with ColorVectorSpace [c3611d14] to versions: [0.7.0-0.7.2, 0.8.0, 0.9.0] — no versions left
   └─ColorVectorSpace [c3611d14] log:
     ├─possible versions are: [0.6.0-0.6.2, 0.7.0-0.7.1, 0.8.0-0.8.2] or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions [0.6.0-0.6.2, 0.7.0-0.7.1, 0.8.0-0.8.2]
`

Since [https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/master/Project.toml](url) seems to suggest SpecialFunctions v0.10.0 should be allowed, my current work-around is to do:

`add https://github.com/JuliaGraphics/ColorVectorSpace.jl`

before adding Images and Luxor.

It seems like the official Julia package "ColorVectorSpace" is not sync to the one here for some reason.

**Comment by timholy** [comment]
Thanks for reporting the problem. Looks like we just needed to issue a new release; this should be fixed by https://github.com/JuliaRegistries/General/pull/8772
