### ISSUE TITLE
`ColorType.gray(x::Real)` is no longer needed

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorVectorSpace.jl#124]
`gray(x::Fractional)` was added in ColorTypes.jl v0.2 (https://github.com/JuliaGraphics/ColorTypes.jl/commit/0b071ed99edb51af3dad159e87d628ad029077c6), and it was modified to `gray(x::Number)` in ColorTypes.jl v0.2.12 (https://github.com/JuliaGraphics/ColorTypes.jl/commit/988de5561009f666b8e9bcce0f0c729b5d90d761).

I think [`Number` is too loose](https://github.com/JuliaGraphics/ColorTypes.jl/issues/162#issuecomment-586128544), but in any case the following is unnecessary:
https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/f2baf1d3e3c9769020692abe747289899d08f35e/src/ColorVectorSpace.jl#L73

**Comment by johnnychen94** [comment]
If I read your words correctly, you suggest to

```diff
# in ColorTypes
- ColorTypes.gray(x::Number) = x
+ ColorTypes.gray(x::Real) = x
```

and by doing this, the same method should be removed here in ColorVectorSpace to avoid redefinition, right? That sounds good to me.

**Comment by kimikage** [comment]
Since `Real<:Number`, the change in ColorTypes.jl is optional. I think there is no ambiguity problem.

**Comment by kimikage** [comment]
I hope this will be fixed, along with other fixes. However, if needed, I will submit a standalone PR.

**Comment by kimikage** [comment]
The PR #131 is going to get rid of the `gray(x::Real)` in ColorVectorSpace.

**Comment by kimikage** [comment]
When I saw PR #137, I thought @timholy was going to make some changes in ColorTypes.jl.
For example: https://github.com/JuliaGraphics/ColorTypes.jl/pull/177/files

However, I don't understand the true intent.

**Comment by kimikage** [comment]
This is a separate issue, but I think the following should be in ColorTypes.jl.

https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/85b8759a24ba8a76c88cbbae714f198490bc92fd/src/ColorVectorSpace.jl#L310
