### ISSUE TITLE
Remove `SpecialFunctions` dep (or replace with `Bessels`)

### ISSUE THREAD

**Issue by t-bltg** [JuliaGraphics/ColorVectorSpace.jl#184]
I can't find why the `SpecialFunctions` dependency was introduced in https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/84.

`SpecialFunctions` is know to trigger lots of dependencies (see the discussions in https://github.com/JuliaMath/SpecialFunctions.jl/issues/409).

If `bessel` functions are required in this package, could you please consider switching to the recent, pure julia https://github.com/JuliaMath/Bessels.jl ?

The `@lazy` approach in https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/182 is interesting, but:
1. it can not be dropped in as usual since `SpecialFunctions` types are used in the module itself;
2. it does not remove `SpecialFunctions` from the list of dependencies.

Cc @juliohm for https://github.com/JuliaPlots/UnicodePlots.jl/issues/291.

**Comment by cormullion** [comment]
I think the Colors/ColorVectorSpace packages are short of maintainers at present. @kimikage has moved on, it seems, and @timholy is doubtless overworked; recruiting some more color specialists is needed!
