### ISSUE TITLE
Broken by FixedPointNumbers

### ISSUE THREAD

**Issue by yuyichao** [JuliaGraphics/ColorVectorSpace.jl#26]
The test fail with `InexactError()` on current master of julia, `ColorTypes`, and `FixexPointNumbers`.

The failing test is dividing a `Gray{U8}` array by `Gray{U8}(0.5)` and it is failing because of an
`InexactError()` during `one(Gray{U8}) / Gray{U8}(0.5)`. I suspect it is related to some ~~not-yet~~ tagged change in `FixedPointNumbers`.

@timholy

**Comment by yuyichao** [comment]
I just confirmed that this is not due to anything on julia master but is caused by FixedPointNumbers (https://github.com/JeffBezanson/FixedPointNumbers.jl/pull/36#issuecomment-158214959)

@vchuravy

**Comment by vchuravy** [comment]
Will look into this

**Comment by yuyichao** [comment]
@vchuravy See @timholy's PR #27 it's an issue in ColorVectorSpace.
