### ISSUE TITLE
Package title and introduction

### ISSUE THREAD

**Issue by rennis250** [JuliaGraphics/ColorVectorSpace.jl#28]
The name of this package is a bit misleading. One might initially assume that it contains some additional vector space construction or something of that sort, whereas those are all contained in ColorTypes.jl. Rather, this package seems to be focused on fast color operations, so perhaps a title like "FastColorOps.jl" or something similar might better illustrate that?

Also, the introduction is a little misleading, too. The basic RGB space, as technically defined, is linear. Some variants of it, such as the sRGB variant, which includes a model of gamma curves for monitors, are non-linear.

Best,
Rob

**Comment by rennis250** [comment]
Actually, upon re-reading, I think I understand the title now. My knowledge of math terminology is very weak. Is there only such a thing as a linear vector space and not a non-linear vector space, such that when one says vector space, there is no ambiguity?

**Comment by yuyichao** [comment]
https://en.wikipedia.org/wiki/Vector_space

> A vector space (also called a linear space)

**Comment by timholy** [comment]
Yeah, I picked the name to indicate that (s)RGB is being treated as a linear vector space. Maybe that's too math-y for the target audience, however. Open to other suggestions.

**Comment by tbreloff** [comment]
> Maybe that's too math-y for the target audience, however

Heh... too math-y for the Julia crowd?  I doubt it. :)

However, what do you think about "ColorMath.jl"?  (or ColorMaths)

**Comment by timholy** [comment]
It's a good name too, but in a sense `Colors` does more "impressive" math with colors (it implements metrics on color spaces, conversions between color spaces, etc). The math done by this package is all "dumb" math, basically applying functions component-wise.

**Comment by tbreloff** [comment]
So then we're in agreement... "DumbColorMath.jl".  I'm eagerly awaiting the julia-users announcement.  ;)

I totally get where you're coming from, and am happy with whatever you want.

**Comment by rennis250** [comment]
Really though, when I think about it now, the title makes perfect sense. No need to make anything less math-y (some of the historical greats in color research were also giants in mathematics :) ). I always value more focus on math, regardless of my skills in that subject. It was just that when I initially went to check the contents of this package, I was expecting to find additional color spaces or something to that effect.

The point about the RGB/sRGB distinction is minor here. I'll open a pull request for that and discussion could continue there.
