### ISSUE TITLE
var()

### ISSUE THREAD

**Issue by bjarthur** [JuliaGraphics/ColorVectorSpace.jl#29]
i'm trying to add support for `var` of a vector of `Gray`, and get a "no matching method" error, despite an entry in the "closest candidates" list which exactly matches the method which it says it cannot find.  there must be something fundamental to julia types that i don't understand.

note that this addresses https://github.com/JuliaGraphics/ColorTypes.jl/issues/34

```
julia> using ColorVectorSpace
                    
julia> import Base.varm

julia> varm(v::Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},1}, s::ColorTypes.Gray{Float64}) = varm(map(gray,v),gray(s))
varm (generic function with 5 methods)

julia> foo = convert(Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}}}, rand(UInt16,10))
10-element Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},1}:
 Gray{UFixed16}(0.36828)
 Gray{UFixed16}(0.64224)
 Gray{UFixed16}(0.94699)
 Gray{UFixed16}(0.13843)
 Gray{UFixed16}(0.94075)
 Gray{UFixed16}(0.98944)
 Gray{UFixed16}(0.61286)
 Gray{UFixed16}(0.19588)
 Gray{UFixed16}(0.77913)
 Gray{UFixed16}(0.15785)

julia> var(foo)
ERROR: MethodError: `varm` has no method matching varm(::Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},1}, ::ColorTypes.Gray{Float64})
Closest candidates are:
  varm(::Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,16}},1}, ::ColorTypes.Gray{Float64})
  varm{T}(::AbstractArray{T,N}, ::Number)
  varm{T}(::AbstractArray{T,N}, ::AbstractArray{T,N}, ::Any)
  ...
 in var at statistics.jl:166
```

**Comment by timholy** [comment]
Wow, that error message is really confusing. I figured this out by following the breadcrumbs:
```jl
@edit var(foo)
```
Look at the code it's calling, and you'll see (at least on 0.4, I don't have a local 0.5 while traveling) it's adding a keyword argument `corrected`, and your implementation doesn't support that keyword. But this doesn't show up in the error message.

Would you mind filing a julia issue about this?
