### ISSUE TITLE
Neither `promote_sys_size_add` nor `r_promote` is  defined in `Base` now

### ISSUE THREAD

**Issue by KDr2** [JuliaGraphics/ColorVectorSpace.jl#85]
Neither `promote_sys_size_add` nor `r_promote` is  defined in `Base` now, but 
https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/master/src/ColorVectorSpace.jl#L56 still tries to refer to them, leads to a loading error.

**Comment by juliohm** [comment]
Yes, this is relevant in Julia v0.7. It would nice to have it fixed in master.

I have packages that I am trying to port that depend on it.

**Comment by timholy** [comment]
Done
